### ISSUE TITLE
Closeable and clear on close

### ISSUE THREAD

**Issue by JanMalch** [xxfast/KStore#105]
Hi, I think it would be useful if the store implements `AutoCloseable` and one can configure the store to delete all data when it's closed. What do you think?

**Comment by xxfast** [comment]
Hi. Do you mean `AutoCloseable` from [Java](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html)? What would be equivalent API / behaviors from other platforms will be?

**Comment by JanMalch** [comment]
There seems to be a multiplatform-ready interface standard library: https://kotlinlang.org/api/core/kotlin-stdlib/kotlin/-auto-closeable/

**Comment by xxfast** [comment]
Hi - apologies for the delayed response. 

> one can configure the store to delete all data when it's closed. What do you think?

Can you walk through a typical usecase for this feature? deleting the file on close feels like an odd behavior for a storage library

**Comment by xxfast** [comment]
> I was thinking about Android's ViewModel. You add the store as a closeable, so that it gets deleted, when the VM isn't in the backstack anymore. This way I can dump lots of data in a cache file, instead of keeping the data in memory, when the VM is in the backstack.

Typically, state preserved on a view model is not expected to be written to disk and only expected to be retained in memory and I feel like this is an undesired feature from a storage library
