### ISSUE TITLE
how can I check if a store exists before calling storeOf function

### ISSUE THREAD

**Issue by SaeedZhiany** [xxfast/KStore#122]
how can I check if a store exists before calling `storeOf` function?  in my application, I want to check whether a store with the given path/key was created before. I don't want to create it if it does not exist.

**Comment by xxfast** [comment]
`KStore` is just a delegate to the underlying file of a given path/storage of a given key. 

You can use the platform APIs to see if the file exists already / key exists already. 
```kotlin
val path =  Path("path/to/myFile")
SystemFileSystem.exists(file) // true if the file exists
```

Typically we always create the stores and observe it's values to determine if a previously written file/key exists or not
```kotlin
val store = storeOf(file = path)
val cat: Cat? = store.get()
if(cat != null) // previously written value exists 
```

**Comment by xxfast** [comment]
Feel free to comment further if you have any more issues.
