### ISSUE TITLE
Can add Private scope storage in Android Platform

### ISSUE THREAD

**Issue by umesh0492** [xxfast/KStore#4]
App specific access -> https://developer.android.com/training/data-storage/app-specific

**Comment by xxfast** [comment]
Hi @umesh0492 

Thanks for the suggestion. I think this can be fulfilled with system configurations as outlined [here](https://github.com/xxfast/KStore#on-android)
```kotlin
val externalFileDir: String? get() = context.getExternalFilesDir().path
val internalFileDir: String get() = context.filesDir.path

actual val fileDir: String? get() = internalFileDir // or externalFileDir depending on usecase 
```

**Comment by xxfast** [comment]
Gonna close this issue for now :) but feel free to reopen if you got further input
