### ISSUE TITLE
There is no 0.7.0 for a desktop target

### ISSUE THREAD

**Issue by terrakok** [xxfast/KStore#71]
https://repo.maven.apache.org/maven2/io/github/xxfast/kstore-desktop/

**Comment by xxfast** [comment]
Hmm.. Looks like i messed something up 🤔 Let me take a look

**Comment by xxfast** [comment]
Weird, the [task](https://github.com/xxfast/KStore/actions/runs/7048152752/job/19183844424#step:6:454) did get executed correctly, but yeah you are right - it didn't seem to make it. Let me try re-running it

**Comment by xxfast** [comment]
And it does show up on staging. Let me try releasing this again 🤞 
<img width="573" alt="Screenshot 2023-12-01 at 8 59 58 am" src="https://github.com/xxfast/KStore/assets/13775137/84834861-5233-4ca5-b032-843c7b24513d">

**Comment by xxfast** [comment]
I've triggered a re-release, on the sonatype dashboard, hopefully that will resolve this issue. Looks like [search](https://status.maven.org/incidents/z7m1hzsgpfqn) was down today, not sure if that has to do with anything. 

In the interim, we can use `0.7.1-SNAPSHOT` - which seems to pull in all the artefacts we need.

**Comment by xxfast** [comment]
`0.7.1` released and available for all platforms 👍
