### ISSUE TITLE
Unresolved reference: storeOf

### ISSUE THREAD

**Issue by davcres** [xxfast/KStore#79]
I have the dependency in the commonMain:
`api("io.github.xxfast:kstore:0.7.1")`

Then I try to create an instance of KStore:
`val store: KStore<UserEntity> = storeOf(filePath = "path/to/my_cats.json")`

But the reference tos storeOf can´t be found.

**Comment by xxfast** [comment]
Hi. Thanks for the issue.

File based stores are now part of `kstore-file` artifacts as of `0.6.0`
```
Implementation("io.github.xxfast:kstore-file:0.7.1")
```

Full documentation on installation  [here](https://xxfast.github.io/KStore/installation.html)

Full documentation on creating a store with platform paths [here](https://xxfast.github.io/KStore/using-platform-paths.html)

**Comment by davcres** [comment]
Thanks!
